export default [
  {
    _id: '1',
    name: 'Pizza',
    imageUrl:
      'https://images.unsplash.com/photo-1513104890138-7c749659a591?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80',
    ingredients: [
      {name: 'Pizza Dough', quantity: 1, unit: 'pcs'},
      {name: 'Cheese', quantity: 3, unit: 'kg'},
      {name: 'Flour', quantity: 1, unit: 'kg'},
      {name: 'Tomato', quantity: 3, unit: 'pcs'},
      {name: 'Mozzarella', quantity: 200, unit: 'gm'},
    ],
    steps: ['hi', 'what', 'yo', 'tespachi', 'idk', 'pizza', 'banyo'],
  },
  {
    _id: '2',
    name: 'Momo',
    imageUrl:
      'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80',
    ingredients: [
      {name: 'Chilli Pepper', quantity: 1, unit: 'pcs'},
      {name: 'Onion', quantity: 3, unit: 'kg'},
      {name: 'Minced Meat', quantity: 1, unit: 'kg'},
      {name: 'Garlic', quantity: 3, unit: 'pcs'},
      {name: 'Mozzarella', quantity: 200, unit: 'gm'},
    ],
    steps: [
      'First do rinse',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
    ],
  },

  {
    _id: '3',
    name: 'Momo',
    imageUrl:
      'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80',
    ingredients: [
      {name: 'Chilli Pepper', quantity: 1, unit: 'pcs'},
      {name: 'Onion', quantity: 3, unit: 'kg'},
      {name: 'Minced Meat', quantity: 1, unit: 'kg'},
      {name: 'Garlic', quantity: 3, unit: 'pcs'},
      {name: 'Mozzarella', quantity: 200, unit: 'gm'},
    ],
    steps: [
      'First do rinse',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
    ],
  },
  {
    _id: '4',
    name: 'Momo',
    imageUrl:
      'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80',
    ingredients: [
      {name: 'Chilli Pepper', quantity: 1, unit: 'pcs'},
      {name: 'Onion', quantity: 3, unit: 'kg'},
      {name: 'Minced Meat', quantity: 1, unit: 'kg'},
      {name: 'Garlic', quantity: 3, unit: 'pcs'},
      {name: 'Mozzarella', quantity: 200, unit: 'gm'},
    ],
    steps: [
      'First do rinse',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
    ],
  },
  {
    _id: '5',
    name: 'Momo',
    imageUrl:
      'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80',
    ingredients: [
      {name: 'Chilli Pepper', quantity: 1, unit: 'pcs'},
      {name: 'Onion', quantity: 3, unit: 'kg'},
      {name: 'Minced Meat', quantity: 1, unit: 'kg'},
      {name: 'Garlic', quantity: 3, unit: 'pcs'},
      {name: 'Mozzarella', quantity: 200, unit: 'gm'},
    ],
    steps: [
      'First do rinse',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
    ],
  },
  // {
  //   _id: '6',
  //   name: 'Momo',
  //   imageUrl:
  //     'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80',
  //   ingredients: [
  //     {name: 'Chilli Pepper', quantity: 1, unit: 'pcs'},
  //     {name: 'Onion', quantity: 3, unit: 'kg'},
  //     {name: 'Minced Meat', quantity: 1, unit: 'kg'},
  //     {name: 'Garlic', quantity: 3, unit: 'pcs'},
  //     {name: 'Mozzarella', quantity: 200, unit: 'gm'},
  //   ],
  //   steps: [
  //     'First do rinse',
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
  //   ],
  // },
  // {
  //   _id: '7',
  //   name: 'Momo',
  //   imageUrl:
  //     'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80',
  //   ingredients: [
  //     {name: 'Chilli Pepper', quantity: 1, unit: 'pcs'},
  //     {name: 'Onion', quantity: 3, unit: 'kg'},
  //     {name: 'Minced Meat', quantity: 1, unit: 'kg'},
  //     {name: 'Garlic', quantity: 3, unit: 'pcs'},
  //     {name: 'Mozzarella', quantity: 200, unit: 'gm'},
  //   ],
  //   steps: [
  //     'First do rinse',
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
  //   ],
  // },
  // {
  //   _id: '8',
  //   name: 'Momo',
  //   imageUrl:
  //     'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80',
  //   ingredients: [
  //     {name: 'Chilli Pepper', quantity: 1, unit: 'pcs'},
  //     {name: 'Onion', quantity: 3, unit: 'kg'},
  //     {name: 'Minced Meat', quantity: 1, unit: 'kg'},
  //     {name: 'Garlic', quantity: 3, unit: 'pcs'},
  //     {name: 'Mozzarella', quantity: 200, unit: 'gm'},
  //   ],
  //   steps: [
  //     'First do rinse',
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste aperiam aliquid unde, corrupti eum molestiae.',
  //   ],
  // },
];
